// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonDb))]
    partial class PokemonDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PokemonAPI.Models.AbilityDao", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Ability");

                    b.HasData(
                        new
                        {
                            Name = "Torrent"
                        },
                        new
                        {
                            Name = "Blaze"
                        },
                        new
                        {
                            Name = "Keen Eye"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonAbilityDao", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbilityName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.HasKey("PokemonId", "AbilityName");

                    b.HasIndex("AbilityName");

                    b.ToTable("PokemonAbility");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            AbilityName = "Torrent",
                            IsHidden = false
                        },
                        new
                        {
                            PokemonId = 2,
                            AbilityName = "Blaze",
                            IsHidden = false
                        },
                        new
                        {
                            PokemonId = 3,
                            AbilityName = "Keen Eye",
                            IsHidden = true
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecialAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attack = 48,
                            Defense = 65,
                            Hp = 44,
                            Name = "Squirtle",
                            SpecialAttack = 50,
                            SpecialDefense = 64,
                            Speed = 43
                        },
                        new
                        {
                            Id = 2,
                            Attack = 52,
                            Defense = 43,
                            Hp = 39,
                            Name = "Charmander",
                            SpecialAttack = 60,
                            SpecialDefense = 50,
                            Speed = 65
                        },
                        new
                        {
                            Id = 3,
                            Attack = 45,
                            Defense = 40,
                            Hp = 40,
                            Name = "Pidgey",
                            SpecialAttack = 35,
                            SpecialDefense = 35,
                            Speed = 56
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeDao", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Name = "Water"
                        },
                        new
                        {
                            Name = "Fire"
                        },
                        new
                        {
                            Name = "Flying"
                        });
                });

            modelBuilder.Entity("PokemonTypes", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypesName")
                        .HasColumnType("TEXT");

                    b.HasKey("PokemonId", "TypesName");

                    b.HasIndex("TypesName");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            TypesName = "Water"
                        },
                        new
                        {
                            PokemonId = 1,
                            TypesName = "Flying"
                        },
                        new
                        {
                            PokemonId = 2,
                            TypesName = "Fire"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonAbilityDao", b =>
                {
                    b.HasOne("PokemonAPI.Models.AbilityDao", null)
                        .WithMany("PokemonAbility")
                        .HasForeignKey("AbilityName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.PokemonDao", null)
                        .WithMany("PokemonAbility")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonTypes", b =>
                {
                    b.HasOne("PokemonAPI.Models.PokemonDao", null)
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.TypeDao", null)
                        .WithMany()
                        .HasForeignKey("TypesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokemonAPI.Models.AbilityDao", b =>
                {
                    b.Navigation("PokemonAbility");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonDao", b =>
                {
                    b.Navigation("PokemonAbility");
                });
#pragma warning restore 612, 618
        }
    }
}
